[LocationID]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=1

[LocationName]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=2

[SunriseTime]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=3

[SunsetTime]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=4

[CurrentTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=5

[CurrentFeelsLike]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=6

[CurrentCondition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=7

[CurrentIcon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=8

[CurrentWindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=9

[CurrentWindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=10

[CurrentWindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=11

[CurrentHumidity]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=12

[CurrentVisibility]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=13

[CurrentHighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=14

[CurrentLowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=15

[Day1HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=16

[Day1LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=17

[Day1Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=18

[Day1Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=19

[Day1WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=20

[Day1WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=21

[Day1WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=22

[Day1PrecipitationChance]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=23

[Day1Humididty]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=24

[Day2HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=25

[Day2LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=26

[Day2Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=27

[Day2Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=28

[Day2WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=29

[Day2WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=30

[Day2WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=31

[Day2PrecipitationChance]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=32

[Day2Humididty]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=33

[Day3HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=34

[Day3LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=35

[Day3Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=36

[Day3Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=37

[Day3WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=38

[Day3WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=39

[Day3WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=40

[Day3PrecipitationChance]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=41

[Day3Humididty]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=42

[Day4HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=43

[Day4LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=44

[Day4Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=45

[Day4Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=46

[Day4WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=47

[Day4WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=48

[Day4WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=49

[Day4PrecipitationChance]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=50

[Day4Humididty]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=51

[Day5HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=52

[Day5LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=53

[Day5Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=54

[Day5Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=55

[Day5WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=56

[Day5WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=57

[Day5WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=58

[Day5PrecipitationChance]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=59

[Day5Humididty]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=60
