[CurrentCondition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=7

[Day1Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=19

[Day2Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=28

[Day3Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=37

[Day4Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=46

[Day5Condition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=55
