[CurrentTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=5

[CurrentFeelsLike]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=6

[CurrentCondition]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=7

[CurrentIcon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=8

[CurrentWindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=9

[CurrentWindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=10

[CurrentWindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=11

[CurrentHumidity]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=12

[CurrentVisibility]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=13

[CurrentHighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=14

[CurrentLowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=15
