[CurrentIcon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=8

[Day1Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=18

[Day2Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=27

[Day3Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=36

[Day4Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=45

[Day5Icon]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=54
