[CurrentTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=5

[CurrentFeelsLike]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=6

[CurrentHighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=14

[CurrentLowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=15

[Day1HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=16

[Day1LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=17

[Day2HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=25

[Day2LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=26

[Day3HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=34

[Day3LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=35

[Day4HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=43

[Day4LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=44

[Day5HighTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=52

[Day5LowTemp]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=53
