[WeatherTime]
measure=Plugin
Plugin=WebParser
URL=[WeatherAll]
StringIndex=1
RegExp=(?siU).*<day d="0" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="1" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="2" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="3" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="4" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="5" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="6" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="7" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="8" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="9" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<day d="10" t="(.*)".*dt="(.*)".*<sunr>(.*)</sunr>.*<suns>(.*)</suns>

[Day0Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=1

[Day0Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=2

[Day0Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=3

[Day0Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=4

[Day1Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=5

[Day1Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=6

[Day1Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=7

[Day1Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=8

[Day2Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=9

[Day2Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=10

[Day2Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=11

[Day2Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=12

[Day3Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=13

[Day3Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=14

[Day3Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=15

[Day3Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=16

[Day4Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=17

[Day4Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=18

[Day4Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=19

[Day4Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=20

[Day5Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=21

[Day5Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=22

[Day5Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=23

[Day5Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=24

[Day6Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=25

[Day6Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=26

[Day6Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=27

[Day6Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=28

[Day7Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=29

[Day7Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=30

[Day7Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=31

[Day7Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=32

[Day8Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=33

[Day8Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=34

[Day8Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=35

[Day8Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=36

[Day9Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=37

[Day9Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=38

[Day9Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=39

[Day9Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=40

[Day10Name]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=41

[Day10Date]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=42

[Day10Sunrise]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=43

[Day10Sunset]
Measure=Plugin
Plugin=WebParser
URL=[WeatherTime]
StringIndex=44