[CurrentWindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=9

[CurrentWindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=10

[CurrentWindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=11

[Day1WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=20

[Day1WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=21

[Day1WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=22

[Day2WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=29

[Day2WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=30

[Day2WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=31

[Day3WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=38

[Day3WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=39

[Day3WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=40

[Day4WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=47

[Day4WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=48

[Day4WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=49

[Day5WindSpeed]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=56

[Day5WindAngle]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=57

[Day5WindBearing]
Measure=Plugin
Plugin=WebParser
URL=[WeatherSite]
StringIndex=58
